### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [doubledherin/my_compiler#1]
Hello, I just discovered this project while searching for learning materials on compilers. Under what license is it released under ? If you don't mind I would like to learn from it. It's very clear for me to read and understand :)

**Comment by doubledherin** [comment]
Hey there,

I just added some info to the readme that indicates what my own learning
materials were. I also added an MIT license.

Have fun!

Wendy

**Comment by suprafun** [comment]
Thank-you so very much : D
